### ISSUE TITLE
required status checks w/ non-owner

### ISSUE THREAD

**Issue by ryanking** [containous/lobicornis#2]
I am getting this error, even thought I've granted the token all the available scopes:

```
2018/01/11 17:00:03 unable to get status checks: GET https://api.github.com/repos/chanzuckerberg/shared-infra/branches/master/protection/required_status_checks: 404 Not Found []
```

I can only get this to work if I make the account running this tool an owner for our organization. Is there another way around this? Do you run with a non-owner account?

**Comment by ldez** [comment]
In this case, you must use the default behavior (eg `--check-up-to-date=false --check-up-to-date=true`):
 ```
--check-up-to-date           Use GitHub repository configuration to check the need to be up-to-date. (default "false")
--force-up-to-date           Forcing need up-to-date. (check-up-to-date must be false)               (default "true")
```

- `--check-up-to-date` if turned to `true` require owner rights.
