### ISSUE TITLE
New flag to support test retries

### ISSUE THREAD

**Issue by shaikatz** [containous/lobicornis#5]
In our CI we have retries on failed tests, but the current implementation of the bot isn't forgiven to failed tests and put the `need-human-merge` tag straight away when he sees any fail test.

I thought about adding --stop-on-failed-tests flag that makes the bot just keep waiting like in `pending` tests.
The default will be set to true to support current behaviour.

Let me know what do you think about that, I'll be happy to implement that.

**Comment by ldez** [comment]
I think about something like that:

```
--marker.retry-prefix   Label use when a retry occurs

--retry-number          Number of retry before failed
```

By default, the retry must be disabled (`retry-number=0`).

In retry mode:
- when a check fails: add the label `merge-retry-1`
- on the next cycle:
  - If the retry label is present, try to merge
  - If unsuccessful, add the label `merge-retry-2`
  - continue until the number is greater than `retry-number`
    - If the checks continue to fail after all retries, add the label `need-human`

**Comment by shaikatz** [comment]
Retry is a bit of a problematic term here, because it depends what are your bot run intervals. I'm running to bot every 1 minute, so if I set the retry-number to 3 it'll fail after 3 minutes although we don't know yet if the retry build was successful because it takes 30 minutes to finish.

**Comment by ldez** [comment]
ok something like that:

```
--marker.retry-prefix   Label use when a retry occurs

--retry.interval        Time between retry
--retry.number          Number of retry before failed
```

**Comment by shaikatz** [comment]
So you propose that when the bot run and sees the retry-prefix it'll first check when the label was added and then only if the delta between the current time and the label insertion time is bigger then interval to try again ? isn't it too complicated? 
I mean, it'll be much easier to have the option to declare: 'I don't want the bot to say that I need human-merge if tests fails, I want the bot to add `waiting-for-tests-to-pass` or something and that's all' ?

**Comment by ldez** [comment]
> I'm running to bot every 1 minute, so if I set the retry-number to 3 it'll fail after 3 minutes although we don't know yet if the retry build was successful because it takes 30 minutes to finish.
If your build are running it's not a problem: because on next cycle if the build is pending the counter will not increase.

**Comment by shaikatz** [comment]
> If your build are running it's not a problem: because on next cycle if the build is pending the counter will not increase.

In my case it takes ~5 minutes for the build to start again, I just feel that it's too risky to coordinate it with the bot runs.

**Comment by ldez** [comment]
I think the problem can be treated as the "merge in progress":
https://github.com/containous/lobicornis/blob/f25cd2c8e679414e8827dc5e10d98d59b3345766/core/core.go#L63-L81

🤔

**Comment by shaikatz** [comment]
Can you elaborate a bit how the two topics can be treated the same?

**Comment by ldez** [comment]
when a fail occurs:
- add `merge-in-progress` and `merge-retry-1`

on the next cycle:
- get all PR in `merge-in-progress` (already exists and it's not possible to have more than 1 or 2 PR)
- browse MIP PR to find a retry
    - check the last updated time
    - if the tile is bigger than interval -> new retry
    - else find a PR with only MIP if exists

**Comment by shaikatz** [comment]
Sounds that it can work. 
Let me try to implement that.
