### ISSUE TITLE
Update PR branch method

### ISSUE THREAD

**Issue by shaikatz** [containous/lobicornis#8]
Hi, 

Currently we do the merge locally on the lobicornis server. 
It can be achieved using github API which will be faster and safer:
https://developer.github.com/v3/repos/merging/

**Comment by ldez** [comment]
Lobicornis already use GitHub API for the merge: 

https://github.com/containous/lobicornis/blob/1dc191594d4e26dfc3d33de8a0f45cba2c141e34/merge/merge.go#L20-L27

**Comment by shaikatz** [comment]
my PR goes into this function when it needs to update the branch from master: 

```
func updatePR(ghub *gh.GHub, issuePR *github.Issue, pr *github.PullRequest, repoID types.RepoID, markers *types.LabelMarkers, gitConfig types.GitConfig, extra types.Extra) error {
	log.Printf("PR #%d: UPDATE", issuePR.GetNumber())

	err := ghub.AddLabels(issuePR, repoID, markers.MergeInProgress)
	if err != nil {
		log.Println(err)
	}

	err = cloneAndUpdate(ghub, pr, gitConfig, extra.DryRun, extra.Debug)
	if err != nil {
		err = ghub.AddLabels(issuePR, repoID, markers.NeedHumanMerge)
		if err != nil {
			log.Println(err)
		}
		err = ghub.RemoveLabel(issuePR, repoID, markers.MergeInProgress)
		if err != nil {
			log.Println(err)
		}
		return err
	}
	return nil
}
```

Why wouldn't it use the github API for the update?

**Comment by ldez** [comment]
The GitHub API don't allow to just rebase without merging.

With the Github API, if you try to do a rebase, the merge is performed before the CI run, and I don't want that.

**Comment by shaikatz** [comment]
But why would you try to do a rebase instead of merge?
My goal is actually to have the same behaviour as the "Update branch" button on the PR that actually merge the master into our feature branch.

**Comment by ldez** [comment]
Rebase or merge it's the same problem: the action is done without run the CI when you are using the GitHub API.

The GitHub API don't have equivalent of the "Update branch" button.

Why rebase?
It's a common way to update a PR, and because it's more simple to alter/fix a rebased branch than a merged branch.
But it's philosophical 😉

**Comment by shaikatz** [comment]
Got you, hope to see this feature implemented in github api.
