### ISSUE TITLE
PR Checks may not be green before merging the PR

### ISSUE THREAD

**Issue by shaikatz** [containous/lobicornis#9]
Just saw the BOT merging a PR without waiting for tests.

Currently this is the Bot flow as documented:

> verify:
GitHub checks (CI, ...)
"Mergeability"
Reviews (--min-review)
check if the PR need to be updated
if yes: rebase or merge with the base PR branch (ex: master)
merge the PR with the chosen merge method. (--merge-method, --marker.merge-method-prefix)
closes related issues and add the same milestone as the PR
if errors occurs add a specific label (--marker.need-human-merge)

The problem here is, after rebasing or merging the base PR branch, the checks needs to rerun to verify that they are still green with the new merged state, but in the current flow, straight after the merge the PR being merged back to master.

**Comment by ldez** [comment]
The checks are re-run after the update of the PR branch.

-> GitHub checks (CI, ...) -> "Mergeability" -> Reviews (--min-review)-> check if the PR need to be updated, if yes:
-  rebase or merge with the base PR branch (ex: master) : update the PR branch (not the PR merge)
- add a label `merge-in-progress`
- do nothing else: don't merge the PR

Sounds weird if it does not happen like that for you, could you give me more details?

**Comment by shaikatz** [comment]
This is the relevant log

`018/02/14 14:34:12 Find PR #325, updated at 2018-02-14 14:33:12 +0000 UTC
2018/02/14 14:34:14 State: pending. Waiting for the CI.
2018/02/14 14:35:14 repo:OwnerName/RepoName type:pr state:open  label:merge-now label:status/4-merge-in-progress  -label:bot/need-human-merge -label:bot/no-merge  review:approved 
2018/02/14 14:35:14 repo:OwnerName/RepoName type:pr state:open  label:merge-now  -label:bot/need-human-merge -label:bot/no-merge  review:approved 
2018/02/14 14:35:15 Find PR #325, updated at 2018-02-14 14:34:10 +0000 UTC
2018/02/14 14:35:17 Merge Base Commit: 816c746088345efb6b8d7054870a03fb8992320f
2018/02/14 14:35:17 Behind By: 1
2018/02/14 14:35:17 PR #325: UPDATE
2018/02/14 14:35:17 Add labels: [status/4-merge-in-progress]. Dry run: false
2018/02/14 14:35:17 Base branch:  master - Fork branch:  branch-name
2018/02/14 14:35:17 /tmp/myrmica-lobicornis983961768
2018/02/14 14:35:17 It's not a fork, it's a branch on the main repository.
2018/02/14 14:35:17 git clone https://TRUNCATED@github.com/OwnerName/RepoName.git .
2018/02/14 14:38:05 git checkout branch-name
2018/02/14 14:38:06 Merge PR #325
2018/02/14 14:38:06 git merge origin/master
2018/02/14 14:38:06 git push origin branch-name
2018/02/14 14:38:09 To https://github.com/OwnerName/RepoName.git
   96c2cd42..9be14246  branch-name -> branch-name

Then on the next run: 

2018/02/14 14:39:10 Find PR #325, updated at 2018-02-14 14:37:53 +0000 UTC
2018/02/14 14:39:11 State: pending. Waiting for the CI.
2018/02/14 14:40:11 repo:OwnerName/RepoName type:pr state:open  label:merge-now label:status/4-merge-in-progress  -label:bot/need-human-merge -label:bot/no-merge  review:approved 
2018/02/14 14:40:12 Find PR #325, updated at 2018-02-14 14:37:53 +0000 UTC
2018/02/14 14:40:13 Merge Base Commit: 61f686643d24cf972f64ae6c544bf63a46960c3a
2018/02/14 14:40:13 Behind By: 0
2018/02/14 14:40:13 PR #325: MERGE(squash)
2018/02/14 14:40:13 Remove label: status/4-merge-in-progress. Dry run: false
2018/02/14 14:40:14 Pull Request successfully merged
2018/02/14 14:40:15 PUT https://api.github.com/repos/OwnerName/RepoName/issues/325/labels: 422 Invalid request.

For 'links/3/schema', nil is not an array. []`

You can see that update happened on 14:38 and in 14:40 it was merged, impossible because our tests run for 20 minutes.

In addition you can see in the end that also there was error removing the label and the Pr was merged with merge-now label. which is weird as well.

**Comment by ldez** [comment]
In the code there are no difference between `merge-in-progress` or `need-merge` PR: all checks are always done.

Maybe an issue with the latency of your CI and GitHub checks.

**Comment by shaikatz** [comment]
Yes that might be the case some race condition between making the PR up to date with the mater and waiting for the checks to be reported as 'started'. 

Do you see any workaround for that?

**Comment by ldez** [comment]
I don't think it's a problem with the up to date state but with the CI response.

Which CI are you using?

**Comment by shaikatz** [comment]
I'm using Teamcity, which report to the github when build was started and finished.

**Comment by ldez** [comment]
I have never use TeamCity, I don't know how are really report the build state.

As workaround, I think you must increase the time between cycle.

**Comment by shaikatz** [comment]
I've increased it. looks better. Thanks
